export interface ITransaction {
  _id: string;
  Id: string;
  user: unknown | null;
  receiver: unknown | null;
  coupon: unknown | null;
  referralCode: string | null;
  amount: number;
  fee: number;
  couponAmount: number;
  exchangeCharge: number;
  Status: string;
  stripeStatus: string;
  currency: string;
  payerMessage: string;
  payeeNote: string;
  referenceId: string;
  externalId: string;
  payee: {
    partyIdType: string;
    partyId: string;
  };
  api: string;
  orginatingCountry: string;
  originalAmount: string;
  originalCurrency: string;
  payerIdentificationType: string;
  payerIdentificationNumber: string;
  payerIdentity: string;
  payerFirstName: string;
  payerSurName: string;
  payerLanguageCode: string;
  payerEmail: string;
  payerMsisdn: string;
  payerGender: string;
  flag: boolean;
  risk: number;
  commission: number;
  transferFee: number;
  cardDetails: string;
  bankAccountDetails: string;
  transactionLocation: string;
  paymentMethod: string;
  cashPickUpMethod: string;
  transactionReviewActivity: unknown[];
  transactionType: string;
  deliveryMethod: string;
  bank: string;
  recipientAccountNumber: string;
  recipientFirstName: string;
  recipientLastName: string;
  recipientPhone: string;
  recipientAddrss1: string;
  recipientAddrss2: string;
  recipientCity: string;
  recipientState: string;
  recipientZipCode: string;
  senderAccountNumber: string;
  senderFirstName: string;
  senderLastName: string;
  senderPhone: string;
  senderAddrss1: string;
  senderAddrss2: string;
  senderCity: string;
  senderState: string;
  senderZipCode: string;
  date: string;
  notes: unknown[];
  createdAt: string;
  updatedAt: string;
  __v: number;
}
